version: '3'
services:
  broker:
    build: broker
    ports:
      - "9000:9000" 
  auldfellas:
    build: auldfellas
    environment:
      SERVICE: auldfellas
    depends_on:
      - broker
  dodgygeezers:
    build: dodgygeezers
    environment:
      SERVICE: dodgygeezers
    depends_on:
      - broker
  girlsallowed:
    build: girlsallowed
    environment:
      SERVICE: girlsallowed
    depends_on:
      - broker
